apiVersion: v1
kind: Service
metadata:
  name: {{ include "your-chart-name.fullname" . }}
  labels:
    app: {{ include "your-chart-name.name" . }}
    chart: {{ include "your-chart-name.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "your-chart-name.name" . }}
    release: {{ .Release.Name }}
